// solidjs/Selector.tsx
import {
  Signal,
  computed,
  exists,
  injectDefaults,
  signal,
  watchDeps,
} from "@/utils";
import { BoxProps, grow, parseSty } from "./Box";
import { Text } from "./Text";
import { Row } from "./Row";
import { Icon } from "./Icon";
import { Modal } from "./Modal";

export function Selector<T>(
  props: {
    value: T;
    getLabelForData: (data: T) => string | null;
    noneLabel?: string;
    modalIsOpen?: Signal<boolean>;
    emptyListText?: string;
    filterString?: Signal<string>;
    showCancelOptionForFilter?: boolean;
    isWide?: boolean;
  } & BoxProps,
) {
  props = injectDefaults(props, {
    noneLabel: `None`,
    emptyListText: `No Options`,
    isWide: false,
  });
  const sty = parseSty(props);
  const selectedLabel = computed(() => {
    return props.getLabelForData(props.value) ?? props.noneLabel;
  });
  const thereAreNoOptions = computed(() => {
    return (
      !exists(props.children) ||
      (Array.isArray(props.children) && props.children.length === 0)
    );
  });

  //
  const _modalIsOpen = signal(props.modalIsOpen?.value ?? false);
  if (exists(props.modalIsOpen)) {
    watchDeps([props.modalIsOpen], () => {
      if (_modalIsOpen.value === props.modalIsOpen!.value) return;
      if (props.modalIsOpen) {
        openDropDown();
      } else {
        closeDropDown();
      }
    });
    watchDeps([_modalIsOpen], () => {
      if (_modalIsOpen.value === props.modalIsOpen!.value) return;
      props.modalIsOpen!.value = _modalIsOpen.value;
    });
  }

  //
  function openDropDown() {
    if (_modalIsOpen.value) return;
    _modalIsOpen.value = true;
  }
  function closeDropDown() {
    if (!_modalIsOpen.value) return;
    _modalIsOpen.value = false;
    if (exists(props.filterString)) {
      props.filterString.value = ``;
    }
  }
  return (
    <Modal
      openButton={
        <Row
          onClick={() => {
            if (exists(props.filterString)) {
              openDropDown();
            } else {
              if (_modalIsOpen.value) {
                _modalIsOpen.value = false;
              } else {
                openDropDown();
              }
            }
          }}
          width={grow()}
          height={sty.scale ?? 1}
          align={$Align.spaceBetween}
        >
          {" "}
          {!exists(props.filterString) || !_modalIsOpen.value ? (
            <Text
              width={grow()}
              overflowX={$Overflow.crop}
              textColor={
                exists(props.value) ? $theme.colors.text : $theme.colors.hint
              }
            >
              {selectedLabel.value}
            </Text>
          ) : (
            <Text width={grow()} hint>
              Search
            </Text>
            // <Field value={props.filterString} hint="Search" hasFocus={true} />
          )}
          <Icon
            icon={
              exists(props.filterString) && _modalIsOpen.value
                ? `close`
                : `menuDown`
            }
            onClick={() => {
              if (_modalIsOpen.value) {
                _modalIsOpen.value = false;
              } else {
                openDropDown();
              }
            }}
          />
        </Row>
      }
      openButtonWidth={grow()}
      openButtonHeight={sty.scale ?? 1}
      isOpen={_modalIsOpen}
      modalWidth={props.isWide ? `100%` : undefined}
    >
      {/* SECTION: No Options */}
      {thereAreNoOptions ? undefined : (
        <Text hint onClick={() => (_modalIsOpen.value = false)} width={grow()}>
          {props.emptyListText}
        </Text>
      )}

      {/* SECTION: Cancel */}
      {exists(props.filterString) &&
      props.showCancelOptionForFilter &&
      !thereAreNoOptions.value ? (
        <Text hint onClick={() => (_modalIsOpen.value = false)} width={grow()}>
          Cancel
        </Text>
      ) : undefined}

      {/* SECTION: Custom Options */}
      {props.children}
    </Modal>
  );
}

// src/Selector.tsx
import { mdiClose, mdiMenuDown } from "@mdi/js";
import { Show } from "solid-js";
import { BoxProps } from "./Box/Box";
import { grow } from "./Box/BoxSize";
import { Field } from "./Field";
import { Icon } from "./Icon";
import { Modal } from "./Modal";
import { Row } from "./Row";
import { Txt } from "./Txt";
import { Prop, useFormula, useProp, exists, doWatch } from "./utils";

export function Selector<T>(
  props: {
    value: T;
    getLabelForData: (data: T) => string | null;
    noneLabel?: string;
    modalIsOpenSig?: Prop<boolean>;
    emptyListText?: string;
    filterStringSig?: Prop<string>;
    showCancelOptionForFilter?: boolean;
    isWide?: boolean;
  } & BoxProps,
) {
  // DEFAULT PROPERTIES
  const noneLabel = useFormula(() => props.noneLabel ?? "None");
  const emptyListText = useFormula(() => props.emptyListText ?? "No Options");
  const isWide = useFormula(() => props.isWide ?? false);
  const _modalIsOpen = useProp(props.modalIsOpenSig?.value ?? false);

  const selectedLabel = useFormula(() => props.getLabelForData(props.value) ?? noneLabel.value);

  const thereAreNoOptions = useFormula(() => {
    return (
      !exists(props.children) || (Array.isArray(props.children) && props.children.length === 0)
    );
  });

  function openDropDown() {
    if (_modalIsOpen.value) return;
    _modalIsOpen.value = true;
  }

  function closeDropDown() {
    if (!_modalIsOpen.value) return;

    _modalIsOpen.value = false;

    if (exists(props.filterStringSig)) {
      props.filterStringSig.value = ``;
    }
  }

  if (exists(props.modalIsOpenSig)) {
    doWatch(
      () => {
        if (!exists(props.modalIsOpenSig)) return;
        if (_modalIsOpen.value === props.modalIsOpenSig.value) return;
        if (props.modalIsOpenSig.value) {
          openDropDown();
        } else {
          closeDropDown();
        }
      },
      {
        on: [props.modalIsOpenSig],
      },
    );
    doWatch(
      () => {
        if (_modalIsOpen.value === props.modalIsOpenSig!.value) return;
        props.modalIsOpenSig!.value = _modalIsOpen.value;
      },
      {
        on: [_modalIsOpen],
      },
    );
  }

  return (
    <Modal
      openButton={
        <Row
          onClick={() => {
            if (exists(props.filterStringSig)) {
              openDropDown();
            } else {
              if (_modalIsOpen.value) {
                _modalIsOpen.value = false;
              } else {
                openDropDown();
              }
            }
          }}
          widthGrows
          height={props.scale ?? 1}
          spaceBetween
        >
          {" "}
          {!exists(props.filterStringSig) || !_modalIsOpen.value ? (
            <Txt
              widthGrows
              overflowX={$Overflow.crop}
              foreground={exists(props.value) ? $theme.colors.text : $theme.colors.hint}
            >
              {selectedLabel.value}
            </Txt>
          ) : (
            <Field value={props.filterStringSig} hintText="Search" hasFocus={useProp(true)} />
          )}
          <Icon
            iconPath={exists(props.filterStringSig) && _modalIsOpen.value ? mdiClose : mdiMenuDown}
            onClick={() => {
              if (_modalIsOpen.value) {
                _modalIsOpen.value = false;
              } else {
                openDropDown();
              }
            }}
          />
        </Row>
      }
      openButtonWidth={grow()}
      openButtonHeight={props.scale ?? 1}
      isOpen={_modalIsOpen}
      modalWidth={isWide.value ? `100%` : undefined}
    >
      {/* SECTION: No Options */}
      <Show when={thereAreNoOptions.value}>
        <Txt hint onClick={() => (_modalIsOpen.value = false)} widthGrows>
          {emptyListText.value}
        </Txt>
      </Show>

      {/* SECTION: Cancel */}
      {exists(props.filterStringSig) &&
      props.showCancelOptionForFilter &&
      !thereAreNoOptions.value ? (
        <Txt hint onClick={() => (_modalIsOpen.value = false)} widthGrows>
          Cancel
        </Txt>
      ) : undefined}

      {/* SECTION: Custom Options */}
      {props.children}
    </Modal>
  );
}
