// solidjs/TabButtons.tsx
import { gsap } from "gsap";
import { Box, BoxProps, grow } from "./Box";
import { Row } from "./Row";
import { createEffect, onMount } from "solid-js";
import { Signal, exists } from "@/utils";
import { Column } from "./Column";

export function TabButtons(
  props: BoxProps & {
    selectedTab: Signal<number>;
    labels?: [string, string, string];
  },
) {
  const labels = props.labels ?? ["Tab 0", "Tab 1", "Tab 2"];
  const tabButtonWidth = 5;
  let tab0Ref: HTMLElement | undefined = undefined;
  let tab1Ref: HTMLElement | undefined = undefined;
  let tab2Ref: HTMLElement | undefined = undefined;
  let tabUnderline: HTMLElement | undefined = undefined;

  function selectTab(newTab: number) {
    if (newTab === props.selectedTab.value) return;
    props.selectedTab.value = newTab;
  }

  createEffect(() => {
    if (exists(tabUnderline)) {
      // Find new position
      const newUnderlinePosition = [
        (tab1Ref?.offsetLeft ?? 0) - (tab2Ref?.offsetLeft ?? 0),
        0,
        (tab2Ref?.offsetLeft ?? 0) - (tab1Ref?.offsetLeft ?? 0),
      ][props.selectedTab.value];

      // console.log(getComputedStyle(tabUnderline));

      // Animate
      gsap.to(tabUnderline, {
        duration: 0.15,
        x: newUnderlinePosition,
        ease: "power1.out",
      });
    }
  });
  return (
    <Column shouldLog={true}>
      <Row
        onClick={props.onClick}
        sty={{
          width: grow(),
          alignX: $Align.spaceAround,
          ...props.sty,
        }}
      >
        <Box
          width={tabButtonWidth}
          ref={(el) => (tab0Ref = el)}
          onClick={() => selectTab(0)}
        >
          {labels[0]}
        </Box>
        <Box
          width={tabButtonWidth}
          ref={(el) => (tab1Ref = el)}
          onClick={() => selectTab(1)}
        >
          {labels[1]}
        </Box>
        <Box
          width={tabButtonWidth}
          ref={(el) => (tab2Ref = el)}
          onClick={() => selectTab(2)}
        >
          {labels[2]}
        </Box>
      </Row>
      <Box
        sty={{
          width: grow(),
          height: 0.375,
          axis: $Axis.stack,
        }}
      >
        <Box
          sty={{
            width: grow(),
            height: 0.375,
            axis: $Axis.row,
            alignX: $Align.spaceAround,
            alignY: $Align.end,
          }}
        >
          <Box sty={{ width: tabButtonWidth }} />
          <Box
            ref={(el) => (tabUnderline = el)}
            sty={{
              width: tabButtonWidth,
              height: 0.125,
              background: $theme.colors.sameAsText,
            }}
          />
          <Box sty={{ width: tabButtonWidth }} />
        </Box>
        <Box
          sty={{
            width: grow(),
            height: 0.375,
            axis: $Axis.row,
            alignX: $Align.spaceAround,
            alignY: $Align.end,
          }}
        >
          <Box
            onClick={() => selectTab(0)}
            sty={{ width: tabButtonWidth, height: grow() }}
          />
          <Box
            onClick={() => selectTab(1)}
            sty={{ width: tabButtonWidth, height: grow() }}
          />
          <Box
            onClick={() => selectTab(2)}
            sty={{ width: tabButtonWidth, height: grow() }}
          />
        </Box>
      </Box>
    </Column>
  );
}

// src/TabButtons.tsx
import { gsap } from 'gsap'
import { Box, BoxProps } from './Box/Box'
import { Row } from './Row'
import { Sig, exists, sig, watchEffect } from './utils'
import { Column } from './Column'
import { Stack } from './Stack'

export function TabButtons(
  props: BoxProps & {
    selectedTab: Sig<number>
    labels?: [string, string, string]
  },
) {
  const tabButtonWidth = 5
  let tab1Ref: HTMLElement | undefined = undefined
  let tab2Ref: HTMLElement | undefined = undefined
  const tabUnderline: Sig<HTMLElement | undefined> = sig(undefined)

  function selectTab(newTab: number) {
    if (newTab === props.selectedTab.value) return
    props.selectedTab.value = newTab
  }

  // Animate Underline
  watchEffect(() => {
    if (exists(tabUnderline.value)) {
      // Find new position
      const newUnderlinePosition = [
        (tab1Ref?.offsetLeft ?? 0) - (tab2Ref?.offsetLeft ?? 0),
        0,
        (tab2Ref?.offsetLeft ?? 0) - (tab1Ref?.offsetLeft ?? 0),
      ][props.selectedTab.value]
      console.log(props.selectedTab.value)

      // Animate
      gsap.to(tabUnderline.value, {
        duration: 0.15,
        x: newUnderlinePosition,
        ease: 'power1.out',
      })
    }
  })

  // Render
  return (
    <Column>
      <Row onClick={props.onClick} widthGrows spaceAroundX overrideProps={props}>
        <Box width={tabButtonWidth} onClick={() => selectTab(0)}>
          {props.labels?.[0] ?? 'Tab 0'}
        </Box>
        <Box width={tabButtonWidth} getElement={el => (tab1Ref = el)} onClick={() => selectTab(1)}>
          {props.labels?.[1] ?? 'Tab 1'}
        </Box>
        <Box width={tabButtonWidth} getElement={el => (tab2Ref = el)} onClick={() => selectTab(2)}>
          {props.labels?.[2] ?? 'Tab 2'}
        </Box>
      </Row>
      <Stack widthGrows height={0.375}>
        <Row widthGrows height={0.375} spaceAroundX alignBottom>
          <Box width={tabButtonWidth} />
          <Box
            getElement={el => (tabUnderline.value = el)}
            width={tabButtonWidth}
            height={0.125}
            background={$theme.colors.sameAsText}
          />
          <Box width={tabButtonWidth} />
        </Row>
        <Row widthGrows height={0.375} spaceAroundX alignBottom>
          <Box onClick={() => selectTab(0)} width={tabButtonWidth} heightGrows />
          <Box onClick={() => selectTab(1)} width={tabButtonWidth} heightGrows />
          <Box onClick={() => selectTab(2)} width={tabButtonWidth} heightGrows />
        </Row>
      </Stack>
    </Column>
  )
}
